if Rails.env.development? || Rails.env.test?

	Dotenv.require_keys(
		'DEVISE_SECRET_KEY',
	    'PUSHER_APP_ID',
	    'PUSHER_KEY',
	    'PUSHER_SECRET',
	    'PUSHER_CLUSTER',
	    'TOKEN_EXPIRATION',
	    'TOKEN_KEY_BASE',
		'DNA_API_URL',
		'DNA_API_KEY'
	)

end

TOKEN_EXPIRATION = ENV['TOKEN_EXPIRATION']
TOKEN_KEY_BASE = ENV['TOKEN_KEY_BASE']
DNA_API_URL = ENV['DNA_API_URL']
DNA_API_KEY = ENV['DNA_API_KEY']
