default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: dna_admin_development

production:
  <<: *default
  database: dna_admin_production

test:
  <<: *default
  database: dna_admin_test
